### ISSUE TITLE
English voice with French words sounds quite bad

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/browser-extension#23]
article: https://www.lefigaro.fr/musique/roger-waters-n-est-pas-le-bienvenu-en-pologne-en-raison-de-ses-prises-de-position-pro-russes-20220926

In the extension it's an English voice that speaks.
If i save to My Texts the voice is correctly French.

**Comment by mircealungu** [comment]
from another user via the Feedback button: 

    Wrt. **url is: https://www.elmundo.es/internacional/2022/08/18/62fd3e16fc6c83e77e8b458f.html and articleId is: 2038647** I'd like to report that: 

The pronunciation is wrong (I am reading a Spanish text).

**Comment by mircealungu** [comment]
Can you try to redeploy the extension?
I've changed some of the speech related code inn the web. I wonder if it
will coincidentally fix also this bug.

M.

**Comment by fribl** [comment]
I have redeployed, but the voice is still wrong. However, now it actually throws an error: "Uncaught TypeError: Cannot read properties of null (reading 'voiceURI')"

**Comment by mircealungu** [comment]
Ok, don’t worry; I’ve looked myself and there are no errors.
Question is: 

did this feature ever work for other languages besides 
danish -- which does not use the TTS but rather uses 
the google API for the pronounciation?

**Comment by mircealungu** [comment]
Fixed for Chrome with: https://github.com/zeeguu/browser-extension/pull/24 and https://github.com/zeeguu/zeeguu-react/commit/0ad10c410403d03e16502ef2d9d624e7db46f2b6. 

However, for Firefox there seems to be no 'tts' permissions, and consequently there is no 'chrome.tts.speak' available :(

**Comment by fribl** [comment]
Nice! It also works in Firefox for me now :) Can you see if it still does not work in Firefox for you?
It has worked in other languages in Chrome at some point - but not sure about Firefox.

**Comment by mircealungu** [comment]
I've fixed it now so it also works in Firefox!

M.

**Comment by Emmategl** [comment]
So, this can be closed?
