### ISSUE TITLE
Allowing me to pronounce a word/phrase multiple times

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/browser-extension#31]
I've just pronounced "Hændelsen skete".
And now I want to pronounce it again, because I didn't hear it well enough.

There's no way for me to do currently to "re-prounounce" except to untranslate the words and translate again.

I wonder if the solution is to add a little speaker button near the last translation, such that one can replay the audio.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/464519/198872355-563a6c00-d3ee-4714-81d2-5c502c934435.png">

"near the last translation" could be debated... the alternative would be to have a little speaker near every translation, but that would end up with visually polluting the text too much maybe?

**Comment by tfnribeiro** [comment]
This feature has now been implemented in both Extension and the Reader.
