### ISSUE TITLE
remember pronounciation preference

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/browser-extension#32]
if a user turns on pronounciation together with translation, save this option in the localstorage and enable it next time. for me, at least, if I read danish, I always like to hear the translations

<img width="796" alt="image" src="https://user-images.githubusercontent.com/464519/198872592-b99234a2-7a3f-4f69-94e8-5b8d527d316f.png">

**Comment by tfnribeiro** [comment]
This has been implemented in https://github.com/zeeguu/browser-extension/pull/55
