### ISSUE TITLE
[BUG] Extension can't click Revise Words and Styling wrong

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/browser-extension#59]
Reading an article with the extension, noticed that the button is with a different styling. It's the same in both browsers.

**Chrome:**
![image](https://github.com/user-attachments/assets/b914f486-a744-4bdc-8cb9-f61e770a320a)

![image](https://github.com/user-attachments/assets/20b5b29d-c2bd-4fd3-8d7b-afab9dfb1fa8)

**Firefox**

![image](https://github.com/user-attachments/assets/5ffb4f43-8040-483e-8c46-76577db5ee72)

![image](https://github.com/user-attachments/assets/f3a82332-019a-469c-89ca-8fb07228db19)

**Comment by mircealungu** [comment]
Good find. I've just submitted the _bugfixed_ version of the extension to the two stores.
